drm: implement mouse cursor
Igalia/cog pull request #234
Opened 2020-10-17 15:08 UTC by kytart

Some inspiration taken from wpebackend-rdk repo.

kms.h and kms.c files are taken directly from libdrm repo almost without change as they contain killer utility functions for working with the KMS objects like planes or CRTCs. The original files can be found here https://gitlab.freedesktop.org/mesa/drm/-/tree/master/tests/kms

cursor-drm.c contains hardcoded cursor bitmap which I took from wpebackend-rdk but scaled it down from 48x48 to 16x16. The original can be found here https://github.com/WebPlatformForEmbedded/WPEBackend-rdk/blob/master/src/bcm-rpi/cursor-data.cpp

I would like to thank @aperezdc for help with this. I wouldn't be able to figure it out myself since I've never really programmed such low level computer graphics before.

2020-10-20 12:54 UTC, zdobersek requested changes

2020-10-20 12:54 UTC, zdobersek commented on platform/cog-platform-drm.c
> +    device = kms_device_open(fd);
As-is, the object is leaked. It should be stored in the drm_data global.

2020-10-20 12:54 UTC, zdobersek commented on platform/cog-platform-drm.c
> +        bool cursorSupported = drmSetClientCap(drm_data.fd, DRM_CLIENT_CAP_UNIVERSAL_PLANES, 1) == 0;
`cursor_supported`

2020-10-20 12:54 UTC, zdobersek commented on platform/cog-platform-drm.c
> +            printf("cursor not supported\n");
Messages should be reported through `g_debug` or `g_warning`, depending on severity.

2020-10-20 12:54 UTC, zdobersek commented on platform/cog-platform-drm.c
> +initialize_cursor(int fd)
Reciprocal clean-up function is missing.

2020-10-20 12:54 UTC, zdobersek commented on platform/cog-platform-drm.c
> +    struct cursor cursor;
This can be a standalone globa. DRM-related object ownership doesn't fit into `input_data`.

2020-11-07 10:59 UTC, kytart commented
@zdobersek I fixed everything you commented on and also I rebased it on top of current master. Please have a look.

2020-11-18 00:08 UTC, aperezdc requested changes
There's a few code style issues, but otherwise I think we could merge this.  
@kytart Could you take a look at the comments? Thanks a lot for working on this, I am really happy to see new contributors learn and write non trivial code like this :muscle: 

For the record, the `kms.h` and `kms.c` files picked from libdrm are under the MIT/X11 license, which is the same we use for Cog, so it's perfectly fine to use them.

2020-11-22 17:24 UTC, kytart commented
@aperezdc I fixed all the issues you pointed out

2020-12-29 18:23 UTC, kytart commented
@aperezdc @zdobersek can we move this forward? It seems that the build have failed but not in anything related to my changes. Is there something I can do?

2021-02-02 23:11 UTC, aperezdc approved these changes
Changes look good, a ton of thanks to @kytart and my apologies for the delay re-reviewing this PR.

The CI build failure is for the WebKitGTK build which has been removed in #257 and so it's not relevant anymore.

Let's merge this!

2021-02-02 23:12 UTC, merged