wl: do not set to null the surface and target at touch_on_up()
Igalia/cog pull request #720
Opened 2024-07-18 11:09 UTC by clopez

On a multitouch screen, when several fingers are on the screen at the same time, if we set to null surface and target on touch_on_up() then we stop all the ongoing touch gestures and not only the one of the finger that caused the up event. That is becasue touch_on_motion() will refuse to process further events if surface or target are null.

Instead of doing that do not set to null this pointers on the touch_on_up() event. The value of those will be set again on the next touch_on_down() event in any case.

Related: https://github.com/Igalia/cog/issues/698
Related: https://bugs.webkit.org/show_bug.cgi?id=270516

2024-07-18 11:50 UTC, psaavedra approved these changes
This looks good to me

2024-08-26 11:58 UTC, aperezdc requested changes
I think it would be better to make `seat->touch_target` a weak reference, that way if the `CogViewport` gets destroyed before the touch-move and/or touch-up events arrive it will be set to `NULL` automatically and we avoid use-after-free of a stale pointer.

When assigning inside `touch_on_down` we want to use:

```diff
-    seat->touch_target = viewport;
+    g_set_weak_pointer(&seat->touch_target, viewport);
```

2024-08-27 09:04 UTC, clopez commented on platform/wayland/cog-platform-wl.c
> +    CogWlViewport *viewport = COG_WL_VIEWPORT(seat->touch_target);
It is already checked at the start of `touch_on_up()`

```
static void
touch_on_up(void *data, struct wl_touch *touch, uint32_t serial, uint32_t time, int32_t id)
{
    if (data == NULL || touch == NULL)
        return;

    CogWlSeat *seat = data;

    if (seat->touch_target == NULL || seat->touch.surface == NULL)
        return;
     //  ^^ here is checked
     // [...] function continues [...]
```

2024-08-27 09:32 UTC, clopez commented
changed: make seat->touch_target a weak reference

2024-08-27 12:03 UTC, aperezdc commented on platform/wayland/cog-platform-wl.c
> +    CogWlViewport *viewport = COG_WL_VIEWPORT(seat->touch_target);
Great, somehow I managed to miss that we had the check already in the code when I was reading the code yesterday. Thanks for pointing it out.

2024-08-27 12:04 UTC, aperezdc approved these changes

2024-08-27 12:05 UTC, merged